"""initial migration

Revision ID: 87dc3057023c
Revises: c7cc451a11dd
Create Date: 2026-04-16 20:52:36.792939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87dc3057023c'
down_revision: Union[str, Sequence[str], None] = 'c7cc451a11dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('records', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('tags', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('tags', 'updated_at')
    op.drop_column('records', 'updated_at')
    op.drop_column('notes', 'updated_at')
    # ### end Alembic commands ###
